// <auto-generated />
using System;
using FlowEngine.Data.EntityFramework.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Demo.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20260531155002_AddResourceLockEvents")]
    partial class AddResourceLockEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Backend.Demo.Domain.FlowBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlowDefinitionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FlowBinding");
                });

            modelBuilder.Entity("Backend.Demo.Domain.InboundOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowDefinitionCode")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FlowTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowVersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InboundOrder");
                });

            modelBuilder.Entity("Backend.Demo.Domain.InboundOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InboundOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetLocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InboundOrderId");

                    b.HasIndex("SkuId");

                    b.HasIndex("TargetLocationId");

                    b.ToTable("InboundOrderLine");
                });

            modelBuilder.Entity("Backend.Demo.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acquired")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentPalletId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPalletId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Backend.Demo.Domain.OutboundOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowDefinitionCode")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FlowTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowVersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OutboundOrder");
                });

            modelBuilder.Entity("Backend.Demo.Domain.OutboundOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutboundOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceLocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OutboundOrderId");

                    b.HasIndex("SkuId");

                    b.HasIndex("SourceLocationId");

                    b.ToTable("OutboundOrderLine");
                });

            modelBuilder.Entity("Backend.Demo.Domain.Pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acquired")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.ToTable("Pallet");
                });

            modelBuilder.Entity("Backend.Demo.Domain.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acquired")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentPalletId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PortType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPalletId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Port");
                });

            modelBuilder.Entity("Backend.Demo.Domain.Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sku");
                });

            modelBuilder.Entity("Backend.Demo.Domain.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("FlowEngine.Execution.Consoles.ConsoleInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Acquired")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConsoleInfo");
                });

            modelBuilder.Entity("FlowEngine.Execution.Consoles.OperationTaskDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomProperties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationTaskType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentFlowTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OperationTaskDetail");
                });

            modelBuilder.Entity("FlowEngine.Execution.Design.FlowDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActiveVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FlowDefinition");
                });

            modelBuilder.Entity("FlowEngine.Execution.Design.FlowDraft", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftDocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FlowDraft");
                });

            modelBuilder.Entity("FlowEngine.Execution.Design.FlowVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompiledGraphJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowDefinitionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeFlowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceDraftRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceGraphJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FlowVersion");
                });

            modelBuilder.Entity("FlowEngine.Execution.FlowEngine.FlowTaskDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionOptionsDetail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentFlowTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FlowTaskDetail");
                });

            modelBuilder.Entity("FlowEngine.Execution.FlowEngine.ResourceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExecutableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExecutableType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FlowTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowTaskId");

                    b.ToTable("ResourceDetail");
                });

            modelBuilder.Entity("FlowEngine.Execution.FlowEngine.ResourceLockEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExecutableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExecutableType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FlowTaskDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FlowTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowTaskDetailId");

                    b.ToTable("ResourceLockEvent");
                });

            modelBuilder.Entity("FlowEngine.Execution.FlowEngine.VariableEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("FlowTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "FlowTaskId");

                    b.HasIndex("FlowTaskId");

                    b.ToTable("VariableEntity");
                });

            modelBuilder.Entity("FlowEngine.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConfirmedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Backend.Demo.Domain.InboundOrderLine", b =>
                {
                    b.HasOne("Backend.Demo.Domain.InboundOrder", "InboundOrder")
                        .WithMany("Lines")
                        .HasForeignKey("InboundOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Demo.Domain.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Demo.Domain.Location", "TargetLocation")
                        .WithMany()
                        .HasForeignKey("TargetLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboundOrder");

                    b.Navigation("Sku");

                    b.Navigation("TargetLocation");
                });

            modelBuilder.Entity("Backend.Demo.Domain.Location", b =>
                {
                    b.HasOne("Backend.Demo.Domain.Pallet", "CurrentPallet")
                        .WithMany()
                        .HasForeignKey("CurrentPalletId");

                    b.HasOne("Backend.Demo.Domain.Warehouse", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentPallet");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Backend.Demo.Domain.OutboundOrderLine", b =>
                {
                    b.HasOne("Backend.Demo.Domain.OutboundOrder", "OutboundOrder")
                        .WithMany("Lines")
                        .HasForeignKey("OutboundOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Demo.Domain.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Demo.Domain.Location", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutboundOrder");

                    b.Navigation("Sku");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("Backend.Demo.Domain.Pallet", b =>
                {
                    b.HasOne("Backend.Demo.Domain.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("Backend.Demo.Domain.Port", b =>
                {
                    b.HasOne("Backend.Demo.Domain.Pallet", "CurrentPallet")
                        .WithMany()
                        .HasForeignKey("CurrentPalletId");

                    b.HasOne("Backend.Demo.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentPallet");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("FlowEngine.Execution.FlowEngine.ResourceDetail", b =>
                {
                    b.HasOne("FlowEngine.Execution.FlowEngine.FlowTaskDetail", "FlowTask")
                        .WithMany("ResourceDetails")
                        .HasForeignKey("FlowTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowTask");
                });

            modelBuilder.Entity("FlowEngine.Execution.FlowEngine.ResourceLockEvent", b =>
                {
                    b.HasOne("FlowEngine.Execution.FlowEngine.FlowTaskDetail", null)
                        .WithMany("ResourceLockEvents")
                        .HasForeignKey("FlowTaskDetailId");
                });

            modelBuilder.Entity("FlowEngine.Execution.FlowEngine.VariableEntity", b =>
                {
                    b.HasOne("FlowEngine.Execution.FlowEngine.FlowTaskDetail", "FlowTask")
                        .WithMany("VariableEntities")
                        .HasForeignKey("FlowTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowTask");
                });

            modelBuilder.Entity("Backend.Demo.Domain.InboundOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Backend.Demo.Domain.OutboundOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Backend.Demo.Domain.Warehouse", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("FlowEngine.Execution.FlowEngine.FlowTaskDetail", b =>
                {
                    b.Navigation("ResourceDetails");

                    b.Navigation("ResourceLockEvents");

                    b.Navigation("VariableEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
